import os
from datetime import datetime

from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import HexColor


def generate_pdf(data, filename="InsightPilot_Report.pdf"):

    styles = getSampleStyleSheet()

    title = styles["Heading1"]
    title.alignment = TA_CENTER
    title.textColor = HexColor("#2563eb")

    heading = styles["Heading2"]
    normal = styles["BodyText"]

    pdf = SimpleDocTemplate(filename)
    story = []

    # ---------------- COVER PAGE ----------------
    story.append(Paragraph("🚀 InsightPilot AI", title))
    story.append(Paragraph("Business Intelligence Report", heading))
    story.append(Spacer(1, 20))

    # ---------------- CHART ----------------
    if os.path.exists("chart.png"):
        story.append(Paragraph("Charts", heading))

        chart = Image("chart.png")
        chart.drawWidth = 450
        chart.drawHeight = 280

        story.append(chart)
        story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            f"<b>Generated :</b> {datetime.now().strftime('%d-%m-%Y %H:%M')}",
            normal
        )
    )

    story.append(Spacer(1, 20))

    # ---------------- DATASET ----------------
    story.append(Paragraph("Dataset Overview", heading))

    story.append(Paragraph(f"<b>Rows :</b> {data.get('rows','-')}", normal))
    story.append(Paragraph(f"<b>Columns :</b> {data.get('columns','-')}", normal))
    story.append(Paragraph(f"<b>Missing Values :</b> {data.get('null_values','-')}", normal))
    story.append(Paragraph(f"<b>Duplicate Records :</b> {data.get('duplicates','-')}", normal))

    story.append(Spacer(1, 20))

    # ---------------- AI SUMMARY ----------------
    story.append(Paragraph("AI Summary", heading))
    story.append(Paragraph(data.get("ai_summary", "No summary available."), normal))
    story.append(Spacer(1, 20))

    # ---------------- BUSINESS STORY ----------------
    story.append(Paragraph("Business Story", heading))
    story.append(Paragraph(data.get("business_story", ""), normal))
    story.append(Spacer(1, 20))

    # ---------------- FINDINGS ----------------
    story.append(Paragraph("Key Findings", heading))

    for item in data.get("key_findings", []):
        story.append(Paragraph(f"• {item}", normal))

    story.append(Spacer(1, 20))

    # ---------------- RECOMMENDATIONS ----------------
    story.append(Paragraph("Recommendations", heading))

    for item in data.get("recommendations", []):
        story.append(Paragraph(f"• {item}", normal))

    story.append(Spacer(1, 30))

    story.append(Paragraph("<b>Generated by InsightPilot AI</b>", heading))

    pdf.build(story)

    return filename