import "./AISummary.css";

function AISummary({ data }) {

    if (!data) return null;

    const summary =
        data.summary ||
        data.ai_summary ||
        data.description ||
        "AI analyzed your dataset and generated business insights.";

    let insights =
        data.findings ||
        data.insights ||
        data.analysis ||
        [];

    if (typeof insights === "string") {

        try {
            insights = JSON.parse(insights);
        }

        catch {

            insights = [insights];

        }

    }

    if (!Array.isArray(insights)) {

        insights = Object.values(insights);

    }

    return (

        <div className="ai-summary-card">

            {/* Header */}

            <div className="ai-header">

                <div className="ai-icon">

                    🧠

                </div>

                <div>

                    <h2>

                        AI Executive Summary

                    </h2>

                    <p>

                        Generated by InsightPilot AI

                    </p>

                </div>

            </div>

            {/* Summary */}

            <div className="summary-box">

                <h3>

                    📋 Executive Overview

                </h3>

                <p>

                    {summary}

                </p>

            </div>

            {/* Findings */}

            <div className="finding-box">

                <h3>

                    🔍 Key Findings

                </h3>

                {

                    insights.length > 0 ?

                        <ul>

                            {

                                insights.slice(0, 6).map((item, index) => (

                                    <li key={index}>

                                        {

                                            typeof item === "object"

                                                ? Object.values(item).join(" ")

                                                : item

                                        }

                                    </li>

                                ))

                            }

                        </ul>

                        :

                        <p>

                            No findings available.

                        </p>

                }

            </div>

            {/* Recommendation */}

            <div className="recommend-box">

                <h3>

                    💡 AI Recommendation

                </h3>

                <p>

                    Review the above findings carefully and focus on improving low-performing business areas while maintaining the strengths identified by the AI analysis.

                </p>

            </div>

        </div>

    );

}

export default AISummary;