import { useState } from "react";
import "./BusinessStory.css";

function BusinessStory({ data }) {

    const [isExpanded, setIsExpanded] = useState(false);

    if (!data || !data.business_story) {
        return null;
    }

    return (

        <div className={`business-story-card ${isExpanded ? "expanded" : ""}`}>

            {/* Header */}

            <div className="story-header">

                <div className="story-icon">

                    📖

                </div>

                <div>

                    <h2>

                        AI Business Story

                    </h2>

                    <p>

                        Executive Narrative Generated by InsightPilot AI

                    </p>

                </div>

            </div>

            {/* Situation */}

            <div className="story-section">

                <h3>

                    📌 Business Situation

                </h3>

                <p>

                    The uploaded dataset has been analyzed to understand business performance, identify trends, and uncover operational patterns.

                </p>

            </div>

            {/* AI Story */}

            <div className="story-section highlight-story">

                <h3>

                    📈 AI Analysis

                </h3>

                <p>

                    {data.business_story}

                </p>

            </div>

            {/* Opportunity */}

            <div className="story-section">

                <h3>

                    🚀 Business Opportunity

                </h3>

                <p>

                    The AI analysis highlights opportunities for improving operational efficiency, increasing revenue, reducing business risks, and supporting better strategic decisions.

                </p>

            </div>

            {/* Recommendation */}

            <div className="story-section recommendation-story">

                <h3>

                    💡 Executive Recommendation

                </h3>

                <p>

                    Use the identified insights together with KPI trends and visual analytics to prioritize high-impact business actions and continuously monitor performance.

                </p>

            </div>

            <button 
                className="mobile-toggle-btn"
                onClick={() => setIsExpanded(!isExpanded)}
            >
                {isExpanded ? "Read Less" : "Read More"}
            </button>

        </div>

    );

}

export default BusinessStory;