import "./Recommendations.css";

function Recommendations({ data }) {

    if (!data) return null;

    let recommendations =
        data.recommendations ||
        data.suggestions ||
        [];

    if (!Array.isArray(recommendations)) {

        if (typeof recommendations === "object") {

            recommendations = Object.values(recommendations);

        }

        else {

            recommendations = [recommendations];

        }

    }

    const priorities = [

        "High",
        "High",
        "Medium",
        "Medium",
        "Low"

    ];

    const icons = [

        "🚀",
        "📈",
        "💰",
        "⚙️",
        "📌"

    ];

    return (

        <div className="recommendation-card">

            <div className="recommendation-header">

                <div className="recommendation-icon">

                    💡

                </div>

                <div>

                    <h2>

                        AI Recommendations

                    </h2>

                    <p>

                        Smart business actions generated by InsightPilot AI

                    </p>

                </div>

            </div>

            <div className="recommendation-grid">

                {

                    recommendations.length > 0 ?

                    recommendations.slice(0,5).map((item,index)=>(

                        <div

                            className="recommendation-item"

                            key={index}

                        >

                            <div className="recommendation-top">

                                <div className="recommendation-emoji">

                                    {icons[index % icons.length]}

                                </div>

                                <span

                                    className={`priority ${priorities[index].toLowerCase()}`}

                                >

                                    {priorities[index]}

                                </span>

                            </div>

                            <h4>

                                Recommendation {index+1}

                            </h4>

                            <p>

                                {

                                    typeof item === "object"

                                    ? Object.values(item).join(" ")

                                    : item

                                }

                            </p>

                        </div>

                    ))

                    :

                    <p>

                        AI recommendations will appear after analysis.

                    </p>

                }

            </div>

        </div>

    );

}

export default Recommendations;